chore: more error handling

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,7 +37,6 @@ jobs:
             end
           ' package.json 2>&1)
           JQ_EXIT_CODE=$?
-          set -e # Re-enable exit on error
 
           if [ $JQ_EXIT_CODE -ne 0 ]; then
             echo "::error::Invalid semver version in package.json"
@@ -45,8 +44,10 @@ jobs:
           fi
 
           ACTION_TAG=$(grep 'image: docker://ghcr.io' action.yml | sed 's/.*://g' | grep -Eo '^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?$')
+          GREP_EXIT_CODE=$?
+          set -e # Re-enable exit on error
 
-          if [ -z "$ACTION_TAG" ]; then
+          if [ $GREP_EXIT_CODE -ne 0 ] || [ -z "$ACTION_TAG" ]; then
             echo "::error::Invalid or missing version format in action.yml"
             exit 3
           fi
